### ISSUE TITLE
ERROR: Module hid_magicmouse is not currently loaded

### ISSUE THREAD

**Issue by fvmsantos** [isdampe/hid-magicmouse#1]
Hi Richard, how are you?

I tried to compile but it didn't work.

My `uname -a` output is:
```
Linux inspiron-7580 5.4.0-52-generic #57~18.04.1-Ubuntu SMP Thu Oct 15 14:04:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
I'm using elementary OS 5.1.7 Hera, built on Ubuntu 18.04.4 LTS.

Thanks for advance!

**Comment by isdampe** [comment]
Hey - what's the error you're getting when you run `make`?

**Comment by fvmsantos** [comment]
Hi, thanks for reply.

It gave no error when running make command, apparently. see the output below:

```
$ make

make -C /lib/modules/5.4.0-52-generic/build M=/home/victor/Projects/hid-magicmouse modules
make[1]: Entering directory '/usr/src/linux-headers-5.4.0-52-generic'
  CC [M]  /home/victor/Projects/hid-magicmouse/hid-magicmouse.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC [M]  /home/victor/Projects/hid-magicmouse/hid-magicmouse.mod.o
  LD [M]  /home/victor/Projects/hid-magicmouse/hid-magicmouse.ko
make[1]: Leaving directory '/usr/src/linux-headers-5.4.0-52-generic'
```
but when I run `sudo rmmod hid-magicmouse` this error happens:

```
rmmod: ERROR: Module hid_magicmouse is not currently loaded
```

**Comment by isdampe** [comment]
Try this:

1. Restart computer
2. Make sure the mouse is connected
3. Run `make clean`
4. Run `make`
5. Run `sudo rmmod hid-magicmouse`
6. Run `sudo insmod hid-magicmouse.ko`

**Comment by fvmsantos** [comment]
my magic mouse 2 is no longer connecting :( so I was trying to compile your code.
when I try to connect by bluetooth manager gives this error:

![image](https://user-images.githubusercontent.com/6462673/98321315-91cac180-1fc3-11eb-8a76-24a061ee775f.png)

**Comment by isdampe** [comment]
That looks like an issue related to bluetooth, not the mouse driver.

Also, if you just restart the computer, your kernel will revert back to the original driver.

**Comment by fvmsantos** [comment]
it was actually a problem with the kernel, it had broken the hid-generic module. I installed a newer kernel and now it is connecting. I'm using the @RicardoEPRodrigues module for the scroll to work.
